[package]
name = "lemillion-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
lemillion-db = { path = "../lemillion-db" }
clap = { version = "4.5.60", features = ["derive"] }
csv = "1.4.0"
comfy-table = "7.2.2"
rand = "0.10.0"
anyhow = "1"
